### ISSUE TITLE
Add "error" response

### ISSUE THREAD

**Issue by osenft** [lowRISC/manticore#25]
Here the use case:

1. Host sends request to device via SPI "WRITE"
1. Device sets SPI "BUSY" bit
1. Host continuously polls SPI "BUSY" bit - potentially forever.
1. Device processes incoming requests.
1. Device generates response and stores it in SPI HW buffer
1. Device clears SPI "BUSY" bit. This releases the SPI interface for subsequent transactions.
1. Host sees SPI "BUSY" bit cleared.
1. Host performs SPI "READ"

The SPI flash protocol requires the "BUSY" bit to be set for a "WRITE" transaction. If the host expects a response for a particular request, it'll perform a "READ" after the "BUSY" bit cleared. One option would be to just send and "invalid" response, e.g. all bytes 0xFF, which would be the default for an "empty SPI flash region".

But it might be useful to give the host a positive response to indicate if there was an error.

**Comment by mcy** [comment]
One way you can do this is by sending a `protocol::Error`, like so:
```
let header = Header { is_request: false, command: CommandType::Error };
let error = protocol::Error {
  code: ErrorCode::Unspecified,
  data: [1, 2, 3, 4],  // Can be whatever you want.
};

header.to_wire(&mut out);
error.to_wire(&mut out);
```

Currently, we don't do this automatically, but that's only because Cerberus doesn't specify values to send back for logic errors. =(

**Comment by osenft** [comment]
Oh, excellent, I think this is sufficient.
