### ISSUE TITLE
Need command line tool to generate and decode messages for manual testing and debugging

### ISSUE THREAD

**Issue by osenft** [lowRISC/manticore#27]
In order to facilitate low level testing and debugging, we need a tool that allows to generate requests in wire format as well as decode both requests and responses from wire format.

**Comment by lenary** [comment]
It would be really cool if we could write this in Rust! I'd love to see more adoption of Rust on the host-side tooling in OpenTitan, and Manticore seems like a great place to start doing so.

**Comment by gkelly** [comment]
> It would be really cool if we could write this in Rust! I'd love to see more adoption of Rust on the host-side tooling in OpenTitan, and Manticore seems like a great place to start doing so.

Totally agree. @osenft I think is already looking at doing this in Rust, I pointed him at structopt for building CLIs.

**Comment by osenft** [comment]
Yes, I have started writing this in Rust using [clap](https://docs.rs/clap/2.33.1/clap/) for CLI stuff. It'll initially implement two things:

- Generate requests and serialize it to a file.
- Deserialize and print messages (requests and responses).

They'll both initially will be limited to what I need for testing the integration of Manticore into [Tock-on-Titan](https://github.com/google/tock-on-titan), but it should be easy to extend as necessary.

**Comment by mcy** [comment]
> It would be really cool if we could write this in Rust! I'd love to see more adoption of Rust on the host-side tooling in OpenTitan, and Manticore seems like a great place to start doing so.

I'll point that Manticore is very much designed to make this possible. It's not just a Cerberus implementation; it also provides libraries for understanding Cerberus data structures.

**Comment by mcy** [comment]
This was implemented in https://github.com/lowRISC/manticore/commit/e9b1a0a22f3b51d27a95dd427f7155ef6afdc479
