### ISSUE TITLE
Clippy not checking tests in CI

### ISSUE THREAD

**Issue by silvestrst** [lowRISC/manticore#80]
It seems that clippy in CI is not running over tests:

```
    - name: Check clippy lints
      run: cargo clippy --verbose
```

I think it might be useful to have an additional:
```
 - name: Check clippy lints
   run:` cargo clippy --tests
```

Unless `--tests` covers both cases, in which case we could just add `--test` to the existing `run`

**Comment by Cypher1** [comment]
I'd recommend using
```
cargo clippy --all-targets
```
to ensure full coverage (though it does sometimes report issues twice: https://github.com/rust-lang/rust-clippy/issues/4092 )
